channels:
- language: ko
  market_focus: BOTH
  username: bornlupin
- language: ko
  market_focus: BOTH
  username: EarlyStock1
- language: ko
  market_focus: BOTH
  username: mimi_ATH
- language: ko
  market_focus: BOTH
  username: one_going
- language: ko
  market_focus: BOTH
  username: aetherjapanresearch
- language: ko
  market_focus: BOTH
  username: awake_realtimeCheck
- language: ko
  market_focus: BOTH
  username: allbareun
- language: ko
  market_focus: BOTH
  username: awake_globalwatch
